utils/helpers.js
Cambié la url de calendly mexico
=> updated mx calendly url

components/CotizationForm/index.jsx
Cambiar preguntas iniciales (paso 2).
Vender auto en la web de MX y comprobar que en el campo "Tipo de factura (MX)" se haya guardado el dato.
La API.
=> Changed variable names and added new options

pages/cotizacion/index.jsx
=> isMinimum from the backend

components/SellForm/index.jsx, components/SellFormChile/index.jsx, components/Toolbar/index.jsx
=> Removed animations

components/head.js, public/static-sitemap/sitemap-ar.xml, public/static-sitemap/sitemap-cl.xml, public/static-sitemap/sitemap-com.xml, public/static-sitemap/sitemap-mx.xml, public/static-sitemap/sitemap-uy.xml
Se agregó los metas "robots", "googlebot" y los sitemaps xml estáticos por dominio.
=> sitemap-xml-static

components/Toolbar/SideDrawer.js
Del menú de navegación mobile se eliminó el link de Blog y se agregó el de Contacto (Whatsapp)
Por favor, revisar el código modificado.
El link hacia el blog en el menú mobile había que eliminarlo.
=> MOBILE - Erased link Blog y add link Contacto

components/head.js, utils/helpers.js
Se mejoró la densidad de palabras en los keywords y se completó datos faltantes en el código.
=> Fix meta head

components/FooterInfo/footerInfo.module.scss, components/FooterInfo/index.jsx, pages/como-comprar/comprar.module.scss, pages/como-comprar/index.jsx, pages/como-vender/index.jsx, pages/como-vender/vender.module.scss, pages/terminos-y-condiciones/index.jsx, utils/helpers.js
Se agregaron 2 nuevas secciones, modificando además el sitemap del footer.
=> Cómo comprar y cómo vender secciones

pages/como-comprar/index.jsx
Se agregó link hacia catálogo sobre el título.
=> Add links a Catálogos

components/Toolbar/SideDrawer.js, components/Toolbar/index.jsx
El CTA tiene como funcionalidad linkear al contacto de Whatsapp específico de cada dominio.
=> Add link Financiamiento

components/head.js, utils/helpers.js
En base a los nuevos resultados de Search Console en términos de búsqueda, optimizamos <meta>
=> Change title, description, keywords

public/autopress-cl.json
=> Removed bad AUTOPRESS values in CL

components/head.js, utils/helpers.js
=> Added Google site verifiaction

public/locales/es-CL/FaqComponent.json
Se reemplazó el término "Automotora" por "Concesionaria"
=> Fix title Automotora

components/FaqCreditosAutos/faq.module.scss, components/FaqCreditosAutos/index.jsx, pages/creditos-para-autos/index.jsx
=> Added accordion to financiamiento

components/FooterInfo/index.jsx
=> Add Link Blog

components/QuoteComponent/quote.module.scss
=> Fix Cursor Pointer

components/QuoteComponent/quote.module.scss
=> Fix Funcionalidad Btn

components/SellForm/index.jsx
=> Change Message CTA

components/head.js
=> Added canonical

components/CustomHeads/headComoComprar.js, components/CustomHeads/headComoVender.js, components/CustomHeads/headTermCond.js
=> Fix CustomHeads Interiores

components/CustomHeads/headComoComprar.js, components/CustomHeads/headComoVender.js, components/CustomHeads/headTermCond.js, components/head.js
=> Add CacheControl Heads

components/NuestrosClientes/nuestrosClientes.module.scss
=> Fix Size Font

components/SellForm/index.jsx
=> Fix altura ventana modal

pages/index/home.module.scss
=> Fix margin title

components/SellForm/index.jsx, components/SellFormChile/index.jsx
CheckBox para seleccionar recepción de newsletter
Dificultad para hacer check sobre el casillero (box).
=> Fix class label

public/locales/es-AR/FooterInfo.json, public/locales/es-CL/FooterInfo.json, public/locales/es-MX/FooterInfo.json
=> Fix Contenido Brand

components/head.js
=> Fix canonical syntaxis

components/CustomHeads/headComoComprar.js, components/CustomHeads/headComoVender.js, components/CustomHeads/headTermCond.js, components/head.js
=> CustomHeads Changes

public/reset.min.css
=> font-display: swap

utils/helpers.js
=> Add new keywords

pages/index.jsx, pages/vender/[brand].js, public/locales/es-AR/common.json, public/locales/es-CL/common.json, public/locales/es-MX/common.json, public/locales/es-UY/common.json
=> Change Text Title

components/Jumbotron/index.jsx, pages/index.jsx, pages/index/home.module.scss
=> Change h1 and h2

components/SellForm/index.jsx, components/SellFormChile/index.jsx, utils/helpers.js
=> Added support for uncovered zones

pages/como-vender/index.jsx
=> Minor fixes CL

utils/helpers.js, yarn.lock
=> Agrego keywords

components/SellForm/index.jsx, components/SellFormChile/index.jsx, public/locales/es-AR/SellForm.json, public/locales/es-CL/SellForm.json, public/locales/es-MX/SellForm.json, public/locales/es-UY/SellForm.json, utils/helpers.js
=> Added phone validation

public/static-sitemap/sitemap-ar.xml
=> Add /creditos-para-autos en Sitemap AR

components/FooterInfo/index.jsx, public/icons/icon-youtube.svg, public/icons/youtube.svg
=> Add YB link

components/SellForm/index.jsx, components/SellFormChile/index.jsx
=> New flow mx + ar

next.config.js, pages/terminos-y-condiciones/index.jsx, yarn.lock
=> Update Changes Términos y Condiciones CL

components/CotizationForm/index.jsx, public/locales/es-AR/CotizationForm.json, public/locales/es-CL/CotizationForm.json, public/locales/es-MX/CotizationForm.json
=> Change UX Writting

components/CotizationForm/index.jsx, public/locales/es-AR/CotizationForm.json, public/locales/es-CL/CotizationForm.json, public/locales/es-MX/CotizationForm.json, yarn.lock
=> Fix Content

pages/terminos-y-condiciones/index.jsx
=> Fix Content T&C

components/CustomHeads/headComoVender.js, components/CustomHeads/headCreditosAutos.js, components/CustomHeads/headTermCond.js, components/head.js
=> Fix content keywords

components/CustomHeads/headComoComprar.js, components/head.js
=> Fix content description

components/SellForm/index.jsx, components/SellFormChile/index.jsx, yarn.lock
=> Added error code to deals with errors

components/SellFormChile/index.jsx
=> Added custom step for undefined cases

components/CustomHeads/headPreguntasFrecuentes.js, components/Toolbar/SideDrawer.js, components/Toolbar/index.jsx, pages/preguntas-frecuentes/index.jsx
=> Add FAQs NavBar

public/static-sitemap/sitemap-ar.xml, public/static-sitemap/sitemap-cl.xml, public/static-sitemap/sitemap-mx.xml, public/static-sitemap/sitemap-uy.xml
=> Update static sitemap

components/CotizationForm/index.jsx, components/QrCode/index.jsx, package.json, yarn.lock
=> Added QR code generator

components/Button/button.module.scss, components/Button/index.jsx, components/ContactForm/contactform.module.scss, components/ContactForm/index.jsx, components/WebInProgress/index.jsx, components/WebInProgress/webinprogress.module.scss, pages/index.jsx
=> Added new fields

components/FaqPreguntasFrecuentesVenderGenerales/index.jsx
=> Updated country data un FAQ

utils/helpers.js
=> Changed Whatsapp phone number

components/Toolbar/index.jsx
=> The store button has been hidden

utils/constants.js
=> Added new Carbula fee

pages/_app.js, pages/_document.js, utils/constants.js, utils/fetches.js
=> Added FB Pixel integration

utils/helpers.js
=> Updated phone numbers

utils/helpers.js
se cambiaron los números de Whatsapp en esta rama
=> editAllWhatsappNumbers

.gitignore, pages/_app.js, pages/_document.js, pages/index.jsx, utils/constants.js
=> implement pixel
